spring:
  datasource:
    url: jdbc:mysql://localhost/userdb?useSSL=false&serverTimezone=UTC
    username: hamitherap
    password: userpass124$
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false