server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/psychologists/**,/api/v1/specializations/**
              filters:
                - StripPrefix=1
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
